[versions]
jackson = "2.21.3"
postgresql = "42.7.11"
testcontainers = "1.21.4"
kotest = "6.2.1"

[libraries]
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonModuleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
testcontainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainersJunit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
