/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("java")

    id("org.springframework.boot") version "3.5.7"
    id("io.spring.dependency-management") version "1.1.0"
    id("org.jetbrains.kotlin.jvm") version "1.9.23"
    id("org.jetbrains.kotlin.plugin.spring") version "1.9.23"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven( "https://repo.spring.io/milestone" )
    maven( "https://repo.spring.io/snapshot" )
}

dependencies {

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:33.5.0-jre")
    implementation("org.postgresql:postgresql:42.7.8")
    implementation("org.junit.jupiter:junit-jupiter:6.0.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.hamcrest:hamcrest-library:3.0")
    implementation("org.testcontainers:testcontainers-postgresql:2.0.1")
    testImplementation("org.testcontainers:testcontainers-junit-jupiter:2.0.1")

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-security")

    implementation("org.flywaydb:flyway-core:11.15.0")
    implementation("org.flywaydb:flyway-database-postgresql")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.postgresql:postgresql:42.7.8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.springframework.boot:spring-boot-starter-test")
    implementation("org.yaml:snakeyaml:2.5")
    implementation("io.arrow-kt:arrow-core:2.1.2")
    testImplementation("org.skyscreamer:jsonassert:1.5.3")
}

kotlin {
  jvmToolchain(21) // Specify JVM target version
  compilerOptions {
    freeCompilerArgs.add("-Xopt-in=kotlin.RequiresOptIn")
  }
}
tasks.test {
  useJUnitPlatform()
}